# Numpy

<div style="text-align: justify"> Numpy menjadi salah satu library dasar pada PyData Ecosystem dan menjadi <em>main building blocks</em> untuk library yang lain. Singkatnya, Numpy merupakan <strong>N-Dimensional Arrays</strong> yang powerful karena cepat dan sebaguna dengan contoh fiturnya yaitu vektorisasi, indexing, dan broadcasting. Numpy juga digunakan sebagai numerical tools karena di dalamnya menyediakan berbagai fungsi matematik. Selain itu, Numpy bisa diaplikasikan di berbagai hardware dan computing platform seperti cloud computing </div>

## Installation

<div style="text-align: justify">Sangat direkomendasikan untuk menginstall python menggunakan Anaconda distribution untuk memastikan semua dependensi Linear Algebra libraries ter-sync up dengan benar. Install Numpy menggunakan terminal atau command prompt kalian dan ketikan :</div>

    conda install numpy

<div style="text-align: justify">Jika kalian tidak memiliki Anaconda dan tidak bisa melakukan instalasi, kunjungin situs official dari Numpy berikut :</div> 


[Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

<div style="text-align: justify">Numpy memiliki banyak built-in function dan kapabilitas, tapi kita akan fokus kepada aspek terpenting pada Numpy yaitu vectors, arrays, matrix, dan number generation</div>

## Numpy Arrays

<div style="text-align: justify">Pada dasarnya terdapat 2 jenis numpy array yaitu vektor dan matrix. Vektor berbentuk array 1 dimensi sedangkan matrix memiliki 2 dimensi atau lebih</div>

### Creating Numpy Arrays Using List

In [1]:
# import library numpy
import numpy as np

**1D Array**

In [2]:
# buat contoh list yang akan diubah menjadi numpy array 1 dimensi
num_list = [1,2,3,4,5]

In [3]:
# cek isi variable num_list
num_list

[1, 2, 3, 4, 5]

In [4]:
# ubah num_list menjadi numpy array
np.array(num_list)

array([1, 2, 3, 4, 5])

**2D Array**

In [5]:
# buat list baru untuk membuat numpy array 2 dimensi (list dalam list)
num_list_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
# cek isi variabel num_list_2d
num_list_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# ubah num_list_2d menjadi numpy array 2 dimensi dengan syntax yang sama dengan sebelumnya 
np.array(num_list_2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perbedaan yang paling mencolok antara array 1d dan 2d yaiu jumlah kurung siku yang terdapat pada hasil outputnya. Pada array 1d terdapat 1 kurung siku :

    array([ ... ])

Sedangkan untuk array 2d memiliki 2 kurung siku :

    array([[ ... ]])

### Creating Numpy Arrays Using Numpy Built-in Method

**arange**

mengembalikan bilangan bulat dengan selisih yang konstan antar bilangan tersebut dan dapat diatur sesuai dengan kebutuhan

In [8]:
# buat numpy array yang memuat angka 0 samapi 9
# terlihat bahwa batas atas tidak termasuk
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# buat numpy array yang memuat bilangan dari 0 samapai 10 dengan step +2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros**

mengembalikan numpy array yang seluruh isinya bernilai nol

In [10]:
# buat 1d numpy array yang berisikan tiga nilai 0
np.zeros(3)

array([0., 0., 0.])

In [14]:
# buat 4 baris, 5 kolom numpy array yang seluruh nilainya adalah 0
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**ones**

mengembalikan numpy array yang seluruh isinya bernilai satu

In [16]:
# buat 1d numpy array yang berisikan empat nilai 1
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
# buat 2 baris, 3 kolom numpy array yang seluruh nilainya adalah 1
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

**linspace**

mengembalikan *evently spaced numbers* pada suatu rentang interval tertentu

In [19]:
# buat numpy array yang berisi 3 bilangan di antara 0 samapi dengan 10 (batas masuk) yang selisih antar bilangannya sama besar 
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
# buat numpy array yang berisi 50 bilangan di antara 0 samapi dengan 10 (batas masuk) yang selisih antar bilangannya sama besar 
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**eye**

mengembalikan matrix identitas

In [21]:
# buat matrix identitas dengan ukuran 5 x 5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random Number Generation

Numpy juga memiliki build-in function untuk membuat array yang terdiri dari bilangan random

**rand**

membuat array dengan bentuk dan dimensi yang dapat dicustom dan berisi sampel bilangan random yang terdistribusi normal antara 0 sampai dengan 1

In [22]:
# buat array 1d dengan 5 buah bilangan random dari 0 sampai 1
np.random.rand(5)

array([0.01708174, 0.94025547, 0.57221219, 0.27119803, 0.52611805])

In [23]:
# buat array 2d dengan dimensi 4 baris x 4 kolom berisi sampel bilangan random yang terdistribusi normal antara 0 sampai 1
np.random.rand(4,4)

array([[0.78561605, 0.53866511, 0.97945888, 0.36953423],
       [0.00998101, 0.75499897, 0.62625016, 0.08829134],
       [0.8538313 , 0.80651766, 0.21897088, 0.06070046],
       [0.35898553, 0.53835329, 0.04748778, 0.55467075]])

**randn**

membuat array berisi sampel bilangan random dari *standard normal distibution* pada interval 0 sampai 1

In [24]:
# buat array 1d berisi 3 sampel bilangan random dari standard normal distribution pada interval 0 sampai 1
np.random.randn(3)

array([-1.06682818, -0.04541571,  0.25650204])

In [25]:
# buat array 2d yang berdimensi 5 baris x 5 kolom berisi sampel bilangan random dari standard normal distribution pada interval 0 sampai 1
np.random.randn(5,5)

array([[ 0.52975098,  1.14090282, -0.60395117, -1.30480023,  0.34745632],
       [ 0.01752918,  0.17434457, -0.20273399, -1.44477422,  0.64957292],
       [-0.91098031, -1.23644848, -0.12164109, -0.43907758,  2.2814509 ],
       [-1.92034429,  0.07668952, -0.11051959,  1.31504758,  0.09335651],
       [ 0.17004517, -1.2365913 ,  1.442803  , -0.41055618,  1.20812428]])

**randint**

membuat array atau mengembalikan nilai bilangan bulat dengan batas bawah (termasuk) dan batas atas (tidak termasuk) yang bisa dicustom

In [26]:
# mengembalikan nilai 1 sampel bilangan bilangan bulat antara 1 (termasuk) sampai 100 (tidak termasuk) secara random
np.random.randint(1,100)

14

In [27]:
# buat array 1d berisi 5 buah sampel bilangan bulat antara 1 (termasuk) sampai 100 (tidak termasuk) secara random
np.random.randint(1,100,5)

array([52, 45, 76, 89, 19])

## Array Attributes and Methods

**arange**

membuat numpy array yang berisi bilangan 0 sampai dengan batas atas - 1 secara berurutan

In [28]:
# buat array dengan method arange dan random.randint
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [29]:
# cek nilai variabel arr
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
# cek nilai variabel ranarr
ranarr

array([26, 15, 22, 45, 14, 40,  8, 26, 36, 11])

Terlihat perbedaan antara arange dan randint yaitu untuk arange bilangan bulat berurutan sedangkan randint bilangan bulat random

**reshape**

mengembalikan array yang memiliki data yang sama tetapi memiliki bentuk yang baru

In [31]:
# perhatikan bahwa hasil kali baris dan kolom harus sama dengan ukuran numpy 1 dimensinya
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max, min, argmax, argmin**

mengembalikan nilai maksimum minimun atau index lokasi dari nilai maksimum minimun tersebut

In [32]:
# cek kembali isi dari variabel ranarr
ranarr

array([26, 15, 22, 45, 14, 40,  8, 26, 36, 11])

In [33]:
# nilai max dari ranarr
ranarr.max()

45

In [34]:
# index dari nilai maksimum pada ranarr
ranarr.argmax()

3

In [35]:
# nilai minimum dari ranarr
ranarr.min()

8

In [36]:
# index dari nilai minimum pada ranarr
ranarr.argmin()

6

**shape**

sebuah atribut array yang mengembalikan dimensi atau ukuran dari array tersebut

In [37]:
# cek dimensi atau ukuran arr
arr.shape

(25,)

In [38]:
# reshape menjadi array 2d dengan dimensi 1 baris x 25 kolom
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
# cek apakah benar dimensi array yang kita maksud
arr.reshape(1,25).shape

(1, 25)

**dtype**

mengembalikan tipe data dari objek pada array

In [41]:
# cek tipe data arr
arr.dtype

dtype('int32')

## Numpy Indexing and Selection

Pada bagian ini kita akan membahas mengenai cara memilih element atau bagian dari numpy array

In [42]:
# buat contoh numpy array
arr = np.arange(0,11)

In [43]:
# cek nilai variabel arr
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection

Cara mengambil element atau *slice of elements* pada numpy array sama dengan ketika melakukan hal tersebut pada python list

In [44]:
# ambil elemen pada index ke 7
arr[7]

7

In [45]:
# ambil bagian dari array yaitu dari index ke 1 sampai dengan 3, ingat batas atas tidak masuk!
arr[1:4]

array([1, 2, 3])

In [46]:
# ambil bagian array dari index ke 3 dst
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Broadcasting

Perbedaan utama antara numpy array dengan python list yaitu kemampuan numpy array untuk mem-broadcast suatu nilai

In [47]:
# me-assign nilai baru pada suatu index range (Broadcasting)
arr[0:4]=999

In [48]:
# cek nilai arr setelah dilakukan Broadcasting
arr

array([999, 999, 999, 999,   4,   5,   6,   7,   8,   9,  10])

In [49]:
# kembalikan kembali nilai arr seperti sebelumnya
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# buat sebuah variabel baru yang menyimpan slice dari arr
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [51]:
# lakukan broadcasting pada numpy array yang baru tersebut
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [52]:
# Lihat! ternyata nilai dari arr juga ikut berganti akibat broadcasting pada slice_of_arr
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Ternyata data arr tidak tercopy ke slice_of_arr, array yang baru tersebut hanya merupakan view dari array asalnya. Numpy memiliki perilaku tersebut untuk menanggulangi masalah memori

In [53]:
# untuk memperoleh copy dari suatu array dapat menggunakan method copy()
arr_copy =  arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
# broadcasting pada array copy dari arr
arr_copy[:]=100

In [56]:
# broadcasting berhasil
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [57]:
# Terlihat bahwa nilai arr tidak berubah
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### Indexing a 2D Array

Terdapat 2 format :
1) Menggunakan 2 kurung siku : arr[row][col]

2) Menggunakan 1 kurung siku dan coma : arr[row,col]

In [58]:
# buat contoh array 2d
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# row indexing
# mengambil element array pada baris dengan index ke-1
arr_2d[1]

array([4, 5, 6])

In [60]:
# getting individual element
# mengambil element array pada baris dengan index ke-1 dan kolom dengan index ke-0
arr_2d[1][0]

4

In [61]:
# getting individual element dengan cara ke 2
arr_2d[2,0]

7

In [62]:
# mengambil slice of 2d array
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [63]:
arr_2d[2:]

array([[7, 8, 9]])

### Selection

Cara melakukan selection pada numpy array sama dengan list yaitu menggunakan notasi kurung siku dan comparison operators

In [64]:
# buat contoh array
arr = np.arange(1,11)

In [65]:
# cek nilai arr
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# element array yang nilainya lebih besar dari 3
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [68]:
# element array yang nilainya lebih kecil dari 7
arr[arr<7]

array([1, 2, 3, 4, 5, 6])

In [69]:
# element array yang nilainya sama dengan 4
arr[arr==4]

array([4])

In [70]:
# kita juga bisa menggunkan variabel sebagai nilai pembandingnya
x = 5
arr[arr>x]

array([ 6,  7,  8,  9, 10])

## Numpy Operations

## Arithmetic

In [71]:
# buat contoh array
arr = np.arange(0,10)

In [72]:
# cek nilai arr
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# penjumlahan
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [74]:
# perkalian
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [75]:
# pengurangan
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
# pebagian
# warning karena 0/0 hasilnya tidak terdefinisi (tapi tidak error)
arr/arr

<ipython-input-76-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
# warning karena 1/0 sama dengan tidak terhingga (inf)
1/arr

<ipython-input-77-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [79]:
# pangkat
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### Universal Array Functions

In [80]:
# pangkat
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
# exponent
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
# nilai max
np.max(arr)

9

In [84]:
# terapkan fungsi sin untuk setiap elemen array
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [85]:
# logaritma
np.log(arr)

<ipython-input-85-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Great Job!